name: jira-description-action
on:
  pull_request:
    types: [opened, edited]
jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    steps:
      - uses: cakeinpanic/jira-description-action@master
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.PERSONAL_JIRA_TOKEN }}
          jira-base-url: https://dg-github-action-test.atlassian.net/
          custom-issue-number-regexp: '^\d+'
          jira-project-key: 'KAN'